language: php

php:
  - 7.2
  - 7.3

sudo: false

install: composer install --prefer-source

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
